// Generated by https://quicktype.io

export interface PinData3 {
    resource_response:  ResourceResponse;
    client_context:     ClientContext;
    resource:           Resource;
    request_identifier: string;
}

export interface ClientContext {
    active_experiments:             ActiveExperiments;
    analysis_ua:                    AnalysisUa;
    app_type_detailed:              number;
    app_version:                    string;
    batch_exp:                      boolean;
    browser_locale:                 string;
    browser_name:                   string;
    browser_type:                   null;
    browser_version:                string;
    country:                        string;
    country_from_hostname:          string;
    country_from_ip:                string;
    csp_nonce:                      string;
    current_url:                    string;
    debug:                          boolean;
    deep_link:                      string;
    enabled_advertiser_countries:   string[];
    experiment_hash:                string;
    facebook_token:                 null;
    full_path:                      string;
    http_referrer:                  string;
    impersonator_user_id:           null;
    invite_code:                    string;
    invite_sender_id:               string;
    is_authenticated:               boolean;
    is_bot:                         string;
    is_internal_ip:                 boolean;
    is_full_page:                   boolean;
    is_mobile_agent:                boolean;
    is_sterling_on_steroids:        boolean;
    is_tablet_agent:                boolean;
    language:                       string;
    locale:                         string;
    origin:                         string;
    path:                           string;
    placed_experiences:             null;
    referrer:                       null;
    region_from_ip:                 string;
    request_host:                   string;
    request_identifier:             string;
    social_bot:                     string;
    stage:                          string;
    sterling_on_steroids_ldap:      null;
    sterling_on_steroids_user_type: null;
    triggerable_experiments:        { [key: string]: string };
    unauth_id:                      string;
    seo_debug:                      boolean;
    user_agent_can_use_native_app:  boolean;
    user_agent_platform:            string;
    user_agent_platform_version:    null;
    user_agent:                     string;
    user:                           User;
    utm_campaign:                   null;
    visible_url:                    string;
}

export interface ActiveExperiments {
    web_lead_gen_ads: string;
}

export interface AnalysisUa {
    app_type:        number;
    browser_name:    string;
    browser_version: string;
    device_type:     null;
    device:          string;
    os_name:         string;
    os_version:      string;
}

export interface User {
    unauth_id:  string;
    ip_country: string;
    ip_region:  string;
}

export interface Resource {
    name:    string;
    options: Options;
}

export interface Options {
    bookmarks:           string[];
    is_own_profile_pins: boolean;
    username:            string;
    field_set_key:       string;
    pin_filter:          null;
}

export interface ResourceResponse {
    status:                        string;
    code:                          number;
    message:                       string;
    endpoint_name:                 string;
    data:                          Datum[];
    bookmark:                      string;
    x_pinterest_sli_endpoint_name: string;
    http_status:                   number;
}

export interface Datum {
    is_video:                          boolean;
    pinner:                            Pinner;
    is_uploaded:                       boolean;
    attribution:                       Attribution | null;
    comment_count:                     number;
    is_eligible_for_related_products:  boolean;
    image_signature:                   string;
    id:                                string;
    is_native:                         boolean;
    reaction_counts:                   ReactionCounts;
    additional_hide_reasons:           any[];
    is_eligible_for_web_closeup:       boolean;
    ad_match_reason:                   number;
    price_value:                       number;
    title:                             string;
    view_tags:                         any[];
    embed:                             null;
    is_downstream_promotion:           boolean;
    tracking_params:                   TrackingParams;
    should_open_in_stream:             boolean;
    method:                            string;
    grid_description:                  string;
    promoter:                          null;
    promoted_is_removable:             boolean;
    is_whitelisted_for_tried_it:       boolean;
    created_at:                        string;
    video_status_message:              null;
    alt_text:                          null | string;
    privacy:                           Privacy;
    done_by_me:                        boolean;
    is_playable:                       boolean;
    sponsorship:                       Sponsorship | null;
    creator_analytics:                 null;
    dominant_color:                    string;
    is_promoted:                       boolean;
    link:                              null | string;
    native_creator:                    Pinner | null;
    story_pin_data_id:                 null | string;
    carousel_data:                     null;
    type:                              DatumType;
    video_status:                      null;
    image_crop:                        ImageCrop;
    videos:                            null;
    promoted_is_lead_ad:               boolean;
    images:                            { [key: string]: Image };
    manual_interest_tags:              null;
    is_oos_product:                    boolean;
    repin_count:                       number;
    board:                             Board;
    comments:                          Comments;
    price_currency:                    PriceCurrency;
    shopping_flags:                    any[];
    product_pin_data:                  null;
    is_eligible_for_pdp:               boolean;
    grid_title:                        string;
    promoted_lead_form:                null;
    debug_info_html:                   null;
    has_required_attribution_provider: boolean;
    story_pin_data:                    StoryPinData | null;
    is_quick_promotable:               boolean;
    description_html:                  string;
    rich_summary:                      RichSummary | null;
    access:                            any[];
    is_stale_product:                  boolean;
    description:                       string;
    aggregated_pin_data:               AggregatedPinData;
    domain:                            string;
    is_repin:                          boolean;
}

export interface AggregatedPinData {
    has_xy_tags:       boolean;
    creator_analytics: null;
    did_it_data:       DidItData;
    aggregated_stats:  AggregatedStats;
    id:                string;
    is_shop_the_look:  boolean;
}

export interface AggregatedStats {
    saves: number;
    done:  number;
}

export interface DidItData {
    tags:              any[];
    recommended_count: number;
    user_count:        number;
    videos_count:      number;
    type:              DidItDataType;
    responses_count:   number;
    images_count:      number;
    recommend_scores:  RecommendScore[];
    details_count:     number;
    rating:            number;
}

export interface RecommendScore {
    score: number;
    count: number;
}

export enum DidItDataType {
    Aggregateddiditdata = "aggregateddiditdata",
}

export interface Attribution {
    provider_name: string;
    url:           string;
    author_name:   string;
    author_url:    string;
    title:         string;
}

export interface Board {
    image_thumbnail_url: string;
    id:                  string;
    layout:              Layout;
    type:                BoardType;
    followed_by_me:      boolean;
    url:                 URL;
    privacy:             Privacy;
    collaborated_by_me:  boolean;
    name:                Name;
    owner:               Pinner;
    is_collaborative:    boolean;
}

export enum Layout {
    Default = "default",
}

export enum Name {
    BrainGains = "Brain Gains",
    Cultures = "Cultures",
    PinterestPredicts2023 = "Pinterest Predicts 2023",
}

export interface Pinner {
    explicitly_followed_by_me: boolean;
    blocked_by_me:             boolean;
    type:                      PinnerType;
    image_small_url:           null | string;
    ads_only_profile_site:     null;
    is_ads_only_profile:       boolean;
    username:                  string;
    full_name:                 string;
    id:                        string;
    image_large_url:           null | string;
}

export enum PinnerType {
    User = "user",
}

export enum Privacy {
    Public = "public",
}

export enum BoardType {
    Board = "board",
}

export enum URL {
    PinterestBrainGains = "/pinterest/brain-gains/",
    PinterestCultures = "/pinterest/cultures/",
    PinterestPinterestPredicts2023 = "/pinterest/pinterest-predicts-2023/",
}

export interface Comments {
    uri:      string;
    data:     any[];
    bookmark: null;
}

export interface ImageCrop {
    min_y: number;
    max_y: number;
}

export interface Image {
    width:  number;
    height: number;
    url:    string;
}

export enum PriceCurrency {
    Usd = "USD",
}

export interface ReactionCounts {
    "1"?: number;
}

export interface RichSummary {
    favicon_images:          { [key: string]: string };
    favicon_link:            string;
    type:                    RichSummaryType;
    products:                any[];
    type_name:               TypeName;
    url:                     string;
    display_name:            string;
    display_description:     string;
    id:                      string;
    apple_touch_icon_images: { [key: string]: string } | null;
    site_name:               string;
    apple_touch_icon_link:   null | string;
    actions:                 any[];
}

export enum RichSummaryType {
    Richpingriddata = "richpingriddata",
}

export enum TypeName {
    Article = "article",
    ClassifierData = "classifier data",
}

export interface Sponsorship {
    sponsor: Pinner;
    creator: Pinner;
    status:  number;
}

export interface StoryPinData {
    page_count:             number;
    pages_preview:          PagesPreview[];
    is_deleted:             boolean;
    type:                   string;
    has_product_pins:       boolean;
    last_edited:            null;
    metadata:               Metadata;
    total_video_duration:   number;
    static_page_count:      number;
    has_affiliate_products: boolean;
    pages:                  Page[];
    id:                     string;
}

export interface Metadata {
    root_user_id:        string;
    template_type:       number | null;
    is_compatible:       boolean;
    recipe_data:         null;
    root_pin_id:         string;
    diy_data:            null;
    compatible_version:  string;
    pin_image_signature: string;
    is_editable:         boolean;
    basics:              Basics | null;
    is_promotable:       boolean;
    pin_title:           string;
    canvas_aspect_ratio: number;
    version:             string;
}

export interface Basics {
    key_value_blocks: KeyValueBlock[];
    list_blocks:      ListBlock[];
}

export interface KeyValueBlock {
    block_type:    number;
    category_type: number;
    type:          string;
    value:         string;
    key:           string;
}

export interface ListBlock {
    heading:    string;
    block_type: number;
    type:       string;
    blocks:     ListBlockBlock[];
}

export interface ListBlockBlock {
    text:       string;
    id:         string;
    block_type: number;
    type:       string;
}

export interface Page {
    blocks: PageBlock[];
}

export interface PageBlock {
    video?:                 Video;
    block_type:             number;
    type?:                  string;
    provider_recording_id?: string;
    audio?:                 Audio;
}

export interface Audio {
    thumbnail_image_url:   string;
    title:                 string;
    artist_name:           string;
    audio_url:             string;
    type:                  string;
    duration:              number;
    description:           string;
    provider_recording_id: string;
    id:                    string;
    royalty_free:          boolean;
}

export interface Video {
    video_list: VideoList;
    id:         string;
    bitrates:   null;
}

export interface VideoList {
    V_EXP7:         VExp3;
    V_EXP6:         VExp3;
    V_EXP3:         VExp3;
    V_EXP5:         VExp3;
    V_HLSV3_MOBILE: VExp3;
    V_EXP4:         VExp3;
}

export interface VExp3 {
    width:             number;
    height:            number;
    duration:          number;
    url:               string;
    thumbnail:         string;
    captions_urls:     CaptionsUrls | null;
    best_captions_url: null;
}

export interface CaptionsUrls {
    "en-us": string;
}

export interface PagesPreview {
    blocks: PagesPreviewBlock[];
}

export interface PagesPreviewBlock {
    video:      Video;
    block_type: number;
}

export enum TrackingParams {
    CwABAAAAEDEzNzMXNjMXODU5NTQ4MTULAACAAAAPDW5Rbm93Bi91Bmtub3DuAA = "CwABAAAAEDEzNzMxNjMxODU5NTQ4MTULAAcAAAAPdW5rbm93bi91bmtub3duAA",
}

export enum DatumType {
    Pin = "pin",
}
