// Generated by https://quicktype.io

export interface PinterestData {
    resource_response: ResourceResponse;
    client_context: ClientContext;
    resource: Resource;
    request_identifier: string;
}

export interface ClientContext {
    active_experiments: ActiveExperiments;
    analysis_ua: AnalysisUa;
    app_type_detailed: number;
    app_version: string;
    batch_exp: boolean;
    browser_locale: string;
    browser_name: string;
    browser_type: number;
    browser_version: string;
    country: string;
    country_from_hostname: string;
    country_from_ip: string;
    csp_nonce: string;
    current_url: string;
    debug: boolean;
    deep_link: string;
    enabled_advertiser_countries: string[];
    experiment_hash: string;
    facebook_token: null;
    full_path: string;
    http_referrer: string;
    impersonator_user_id: null;
    invite_code: string;
    invite_sender_id: string;
    is_authenticated: boolean;
    is_bot: string;
    is_internal_ip: boolean;
    is_full_page: boolean;
    is_managed_advertiser: boolean;
    is_mobile_agent: boolean;
    is_shop_the_pin_campaign_whitelisted: boolean;
    is_sterling_on_steroids: boolean;
    is_tablet_agent: boolean;
    language: string;
    locale: string;
    origin: string;
    path: string;
    placed_experiences: null;
    referrer: null;
    region_from_ip: string;
    request_host: string;
    request_identifier: string;
    social_bot: string;
    stage: string;
    sterling_on_steroids_ldap: null;
    sterling_on_steroids_user_type: null;
    triggerable_experiments: { [key: string]: string };
    unauth_id: string;
    seo_debug: boolean;
    user_agent_can_use_native_app: boolean;
    user_agent_platform: string;
    user_agent_platform_version: null;
    user_agent: string;
    user: User;
    utm_campaign: null;
    visible_url: string;
}

export interface ActiveExperiments {
}

export interface AnalysisUa {
    app_type: number;
    browser_name: string;
    browser_version: string;
    device_type: null;
    device: string;
    os_name: string;
    os_version: string;
}

export interface User {
    is_partner: boolean;
    verified_domains: any[];
    email: string;
    type: UserType;
    phone_number_end: string;
    nags: any[];
    is_high_risk: boolean;
    last_name: string;
    website_url: null;
    connected_to_facebook: boolean;
    has_password: boolean;
    third_party_marketing_tracking_enabled: boolean;
    domain_verified: boolean;
    gender: string;
    image_large_url: string;
    ads_only_profile_site: null;
    id: string;
    phone_number: null;
    connected_to_dropbox: boolean;
    age_in_years: number;
    epik: string;
    image_small_url: string;
    connected_to_etsy: boolean;
    connected_to_google: boolean;
    show_personal_boutique: boolean;
    is_matured_new_user: boolean;
    connected_to_microsoft: boolean;
    is_employee: boolean;
    personalize_from_offsite_browsing: boolean;
    ip_country: string;
    has_mfa_enabled: boolean;
    is_any_website_verified: boolean;
    can_enable_mfa: boolean;
    push_package_user_id: string;
    has_quicksave_board: boolean;
    connected_to_youtube: boolean;
    domain_url: null;
    partner: null;
    unverified_phone_number_without_country: string;
    is_write_banned: boolean;
    twitter_publish_enabled: boolean;
    allow_personalization_cookies: null;
    facebook_id: string;
    facebook_publish_stream_enabled: boolean;
    country: string;
    gplus_url: null;
    facebook_timeline_enabled: boolean;
    image_medium_url: string;
    resurrection_info: null;
    twitter_url: null;
    allow_analytic_cookies: null;
    allow_marketing_cookies: null;
    profile_discovered_public: null;
    unverified_phone_number: null;
    ip_region: string;
    custom_gender: null;
    verified_identity: ActiveExperiments;
    created_at: string;
    login_state: number;
    unverified_phone_country: null;
    username: string;
    full_name: string;
    first_name: string;
    phone_country: null;
    image_xlarge_url: string;
    listed_website_url: null;
    is_ads_only_profile: boolean;
    connected_to_instagram: boolean;
    verified_user_websites: any[];
}

export enum UserType {
    User = "user",
}

export interface Resource {
    name: string;
    options: Options;
}

export interface Options {
    bookmarks: string[];
    board_id: string;
    board_url: string;
    currentFilter: number;
    field_set_key: string;
    filter_section_pins: boolean;
    sort: string;
    layout: string;
    page_size: number;
    redux_normalize_feed: boolean;
}

export interface ResourceResponse {
    status: string;
    code: number;
    data: PinData[];
    message: string;
    endpoint_name: string;
    x_pinterest_sli_endpoint_name: string;
    http_status: number;
}

export interface PinData {
    isDownloaded: any;
    repin_count?: number;
    is_eligible_for_related_products?: boolean;
    is_native?: boolean;
    category?: string;
    dominant_color?: string;
    grid_title?: string;
    rich_summary?: RichSummary | null;
    access?: Access[];
    is_quick_promotable?: boolean;
    has_required_attribution_provider?: boolean;
    image_crop?: ImageCrop;
    unified_user_note?: UnifiedUserNote;
    board?: Board;
    shopping_flags?: number[];
    debug_info_html?: null;
    promoted_is_removable?: boolean;
    attribution?: null;
    favorite_user_count?: number;
    promoter?: Pinner | null;
    id: string;
    aggregated_pin_data?: AggregatedPinData;
    tracking_params: TrackingParams;
    alt_text?: null;
    image_signature?: string;
    is_repin?: boolean;
    carousel_data?: null;
    story_pin_data_id?: null | string;
    images?: { [key: string]: Image };
    is_stale_product?: boolean;
    embed?: null;
    description: UnifiedUserNote | null;
    is_promoted?: boolean;
    done_by_me?: boolean;
    reaction_counts?: { [key: string]: number };
    videos?: Videos | null;
    favorited_by_me?: boolean;
    sponsorship?: null;
    link?: null | string;
    type: DatumType;
    product_pin_data?: null;
    is_downstream_promotion?: boolean;
    story_pin_data?: StoryPinData | null;
    domain?: string;
    is_eligible_for_pdp?: boolean;
    video_status?: null;
    native_creator?: Pinner | null;
    video_status_message?: null;
    creator_analytics?: null;
    pinner?: Pinner;
    is_oos_product?: boolean;
    title: TitleClass | string;
    dynamic_insertion_options?: ActiveExperiments;
    background_colour?: null;
    content_ids?: string[];
    experience?: null;
    button_text?: null;
    copy?: ActiveExperiments;
    display_options?: DisplayOptions;
    slot?: null;
    shop_source?: null;
    item_actions?: any[];
    user?: null;
    bookmarks_for_objects?: null;
    expanded_viewport_objects?: any[];
    container_type?: number;
    referring_source?: string;
    story_type?: string;
    mapped_display_options?: ActiveExperiments;
    objects?: Object[];
    custom_properties?: ActiveExperiments;
    closeup_id?: null;
    subtitle?: null;
    aux_fields?: ActiveExperiments;
    relationships?: ActiveExperiments;
    action?: ActiveExperiments;
    experience_extra_context?: ActiveExperiments;
}

export enum Access {
    Delete = "delete",
    Write = "write",
}

export interface AggregatedPinData {
    is_shop_the_look: boolean;
    id: string;
    did_it_data: DidItData;
    aggregated_stats: AggregatedStats;
    has_xy_tags: boolean;
    creator_analytics: null;
    pin_tags_chips?: PinTagsChip[];
}

export interface AggregatedStats {
    saves: number;
    done: number;
}

export interface DidItData {
    rating: number;
    tags: any[];
    images_count: number;
    recommend_scores: RecommendScore[];
    user_count: number;
    recommended_count: number;
    responses_count: number;
    videos_count: number;
    type: DidItDataType;
    details_count: number;
}

export interface RecommendScore {
    score: number;
    count: number;
}

export enum DidItDataType {
    Aggregateddiditdata = "aggregateddiditdata",
}

export interface PinTagsChip {
    id: string;
    images: { [key: string]: Image };
    image_signature: string;
    link: string;
    price_currency: null;
    price_value: null;
    title: null;
    dominant_color: DominantColor;
}

export enum DominantColor {
    Ebaf90 = "#ebaf90",
    F1Dfbf = "#f1dfbf",
    Fffefe = "#fffefe",
    Ffffff = "#ffffff",
}

export interface Image {
    width: number;
    height: number;
    url: string;
}

export interface Board {
    owner: Pinner;
    id: string;
    url: string;
    collaborated_by_me: boolean;
    privacy: Privacy;
    is_collaborative: boolean;
    name: string;
    followed_by_me: boolean;
    type: BoardType;
}

export interface Pinner {
    full_name: string;
    id: string;
    image_medium_url: string;
    last_name: LastName;
    image_small_url: string;
    image_xlarge_url: string;
    image_large_url: string;
    first_name: string;
    type: UserType;
    username: string;
}

export enum LastName {
    Empty = "",
    Samaro = "Samaro",
    Tea = "Tea",
}

export enum Privacy {
    Public = "public",
}

export enum BoardType {
    Board = "board",
}

export enum UnifiedUserNote {
    Empty = " ",
    UnifiedUserNote = "",
}

export interface DisplayOptions {
    image_only: null;
    subtitle_text_color: null;
    content_display: null;
    action_button_location: null;
    extra_spacing_after: number;
    title_text_color: null;
    hide_search_guides_when_visible: boolean;
    header_hidden: boolean;
    identifier_icon_name: null;
    hide_education_in_stream: null;
    num_columns_requested: number;
    show_simplified_pin: boolean;
    pin_display_options: null;
    footer_display: null;
    item_view_rep_style: null;
    align_image_bottom: boolean;
    extra_spacing_before: number;
    allow_pin_height_trimming: null;
    show_follow_buttons: null;
    pin_image_ratio: null;
    header_display: null;
    carousel_item_spacing: null;
    shopping_grid_display: null;
    item_column_span: null;
    container_grid_span: null;
    corner_radius: null;
    tiles_grid_layout: null;
    use_plain_text_display_mode: boolean;
    show_product_indicator_overlay: null;
    has_condensed_header: boolean;
    hide_ui_in_stream: null;
    ideas_card_hide_when_offscreen: boolean;
    header_font: null;
    horizontal_full_bleed: boolean;
    carousel_fade_ends: null;
    show_content_follow_buttons: null;
    board_view_type: null;
    show_dismiss_button: null;
    scale_up: null;
}

export interface ImageCrop {
    min_y: number;
    max_y: number;
}

export interface Object {
    owner?: Pinner;
    id: string;
    url?: string;
    collaborated_by_me?: boolean;
    privacy?: Privacy;
    is_collaborative?: boolean;
    name?: string;
    followed_by_me?: boolean;
    type: string;
    repin_count?: number;
    is_eligible_for_related_products?: boolean;
    is_native?: boolean;
    category?: string;
    dominant_color?: string;
    grid_title?: string;
    rich_summary?: RichSummary | null;
    access?: any[];
    is_quick_promotable?: boolean;
    has_required_attribution_provider?: boolean;
    image_crop?: ImageCrop;
    unified_user_note?: UnifiedUserNote | null;
    board?: Board;
    shopping_flags?: any[];
    debug_info_html?: null;
    promoted_is_removable?: boolean;
    attribution?: null;
    favorite_user_count?: number;
    promoter?: null;
    aggregated_pin_data?: AggregatedPinData;
    tracking_params?: TrackingParams;
    alt_text?: null;
    image_signature?: string;
    is_repin?: boolean;
    carousel_data?: null;
    story_pin_data_id?: null;
    images?: { [key: string]: Image };
    is_stale_product?: boolean;
    embed?: null;
    description?: UnifiedUserNote;
    is_promoted?: boolean;
    done_by_me?: boolean;
    reaction_counts?: ReactionCounts;
    videos?: null;
    favorited_by_me?: boolean;
    sponsorship?: null;
    link?: null | string;
    product_pin_data?: null;
    is_downstream_promotion?: boolean;
    story_pin_data?: null;
    domain?: string;
    is_eligible_for_pdp?: boolean;
    video_status?: null;
    native_creator?: Pinner | null;
    video_status_message?: null;
    creator_analytics?: null;
    pinner?: Pinner;
    is_oos_product?: boolean;
    title?: string;
}

export interface ReactionCounts {
    "1"?: number;
}

export interface RichSummary {
    type_name: string;
    display_description: string;
    site_name: string;
    favicon_images: { [key: string]: string };
    type: string;
    display_name: string;
    products: any[];
    id: string;
    url: string;
    actions: any[];
    favicon_link: string;
    apple_touch_icon_images: { [key: string]: string };
    apple_touch_icon_link: string;
    is_soft_404?: boolean;
}

export enum TrackingParams {
    CwABAAAAEDQ2MTkzMTYwMTg4MTY5MzcGAAMAAQA = "CwABAAAAEDQ2MTkzMTYwMTg4MTY5MzcGAAMAAQA",
    CwABAAAAEDQ2MTkzMTYwMTg4MTY5MzcGAAMAAQsABWAAAApuZ2FwaS9Wcm9KAA = "CwABAAAAEDQ2MTkzMTYwMTg4MTY5MzcGAAMAAQsABwAAAApuZ2FwaS9wcm9kAA",
}

export interface StoryPinData {
    page_count: number;
    id: string;
    is_deleted: boolean;
    last_edited: null;
    pages_preview: PagesPreview[];
    pages: Page[];
    has_product_pins: boolean;
    static_page_count: number;
    has_affiliate_products: boolean;
    total_video_duration: number;
    type: string;
    metadata: Metadata;
}

export interface Metadata {
    root_pin_id: string;
    pin_image_signature: string;
    compatible_version: string;
    recipe_data: null;
    root_user_id: string;
    diy_data: null;
    template_type: null;
    is_compatible: boolean;
    canvas_aspect_ratio: number;
    is_promotable: boolean;
    basics: null;
    version: string;
    pin_title: string;
    is_editable: boolean;
}

export interface Page {
    blocks: PageBlock[];
}

export interface PageBlock {
    block_type: number;
    video?: Video;
    block_style?: BlockStyle;
    tracking_id?: string;
    type?: string;
    text?: string;
    image?: null;
    image_signature?: string;
}

export interface BlockStyle {
    x_coord: number;
    width: number;
    corner_radius: number;
    rotation: number;
    height: number;
    y_coord: number;
}

export interface Video {
    video_list: VideoVideoList;
    id: string;
    bitrates: null;
}

export interface VideoVideoList {
    V_EXP6: VEXP3Class;
    V_EXP5: VEXP3Class;
    V_EXP3: VEXP3Class;
    V_HLSV3_MOBILE: VEXP3Class;
    V_EXP7: VEXP3Class;
    V_EXP4: VEXP3Class;
}

export interface VEXP3Class {
    width: number;
    height: number;
    duration: number;
    url: string;
    thumbnail: string;
    captions_urls: null;
    best_captions_url: null;
}

export interface PagesPreview {
    blocks: PagesPreviewBlock[];
}

export interface PagesPreviewBlock {
    block_type: number;
    video: Video;
}

export interface TitleClass {
    text: null;
    args: any[];
    format: string;
}

export enum DatumType {
    Pin = "pin",
    Story = "story",
}

export interface Videos {
    id: string;
    video_list: VideosVideoList;
}

export interface VideosVideoList {
    V_HLSV4: PurpleVExp3;
    V_HLSV3_WEB: PurpleVExp3;
    V_HLSV3_MOBILE: PurpleVExp3;
    V_EXP3?: PurpleVExp3;
    V_EXP4?: PurpleVExp3;
    V_EXP5?: PurpleVExp3;
    V_EXP6?: PurpleVExp3;
    V_EXP7?: PurpleVExp3;
}

export interface PurpleVExp3 {
    url: string;
    width: number;
    height: number;
    duration: number;
    thumbnail: string;
}
