// Generated by https://quicktype.io

export interface PinterestImageJSON {
    key:         string;
    value:       Value;
    contentType: string;
}

export interface Value {
    type: string;
    data: number[];
}
